package web

// lang holds every user-visible string of the panel (RN2's App/Lang/en.php
// verbatim). English only for now; the map is the seam where translations
// return.
var lang = map[string]string{
	"admin":                        "Admin",
	"admin_delete_confirm_header":  "Confirm Deletion",
	"admin_capture_delete_warning": "Click the dust bin next to the captures you want to delete to have both the pass/capture removed from the database and all associated images deleted. **WARNING**: This is irreversible, so please ensure this is what you want!",
	"admin_pass_delete_warning":    "Click the dust bin next to the passes you want to delete to have the pass unscheduled and removed from the database. **WARNING**: This is irreversible, so please ensure this is what you want!",
	"cancel":                       "Cancel",
	"captures":                     "Captures",
	"completed_pass":               "Processing finished",
	"reception_status":             "Status",
	"confirm":                      "Confirm",
	"conflicting_pass":             "Conflict with previous pass",
	"skipped_pass":                 "Not scheduled",
	"elev":                         "Elevation",
	"enhancement":                  "Enhancement",
	"fail_delete_missing_id":       "Failed to delete - missing 'id' parameter",
	"filter_all":                   "All",
	"filter_apply":                 "Filter",
	"filter_clear":                 "Clear",
	"filter_day":                   "Day",
	"filter_daynight":              "Day/Night",
	"filter_night":                 "Night",
	"fullscreen":                   "Fullscreen",
	"close":                        "Close",
	"gain":                         "Gain",
	"image":                        "Image",
	"live_status":                  "Live status",
	"next_pass_label":              "Next pass",
	"images":                       "Images",
	"max_elev":                     "Max Elevation",
	"max_snr":                      "Peak SNR",
	"avg_snr":                      "Avg SNR",
	"frames":                       "frames",
	"frame_yield":                  "Frames",
	"frame_loss":                   "Frame loss",
	"frames_received":              "Frames received",
	"largest_frame_gap":            "Largest gap",
	"next":                         "Next",
	"next_pass":                    "Waiting for next pass",
	"no_capture_pass":              "No valid capture or image processing in progress",
	"failed_pass":                  "Capture failed",
	"processing_pass":              "Capture complete, decoding images...",
	"of":                           "of",
	"page":                         "Page",
	"pass_end":                     "Pass End",
	"pass_start":                   "Pass Start",
	"pass_start_azimuth":           "Azimuth",
	"passes":                       "Passes",
	"prev":                         "Prev",
	"running_pass":                 "Capture in progress...",
	"satellite":                    "Satellite",
	"stats":                        "Stats",
	"station_record":               "Station record",
	"recording_since":              "Recording since",
	"no_record_yet":                "No passes decoded yet",
	"captures_decoded":             "Captures decoded",
	"all_time":                     "all time",
	"passes_completed":             "Passes completed",
	"attempted_in_30d":             "attempted in 30 days",
	"none_attempted_30d":           "none attempted in 30 days",
	"strongest_signal":             "Strongest signal",
	"peak_snr_recorded":            "peak SNR on record",
	"recorder_alt":                 "Passes per day over the last 30 days, decoded and failed",
	"mean":                         "mean",
	"per_day_suffix":               "/day",
	"decoded":                      "decoded",
	"failed":                       "failed",
	"last_30_days":                 "Last 30 days",
	"per_satellite":                "Per satellite",
	"snr_bar_note":                 "SNR bars scale to the station peak",
	"avg_elev":                     "Avg elevation",
	"best_snr":                     "Best SNR",
	"avg_frame_loss":               "Avg frame loss",
	"last_capture":                 "Last capture",
	"daily_mosaic":                 "Daily mosaic",
	"download":                     "Download",
	"timelapse":                    "Timelapse",
	"one_per_projection":           "one per projection",
	"all_projections":              "all projections",
	"no_captures_yet":              "Nothing decoded yet. Satellites appear here after their first successful pass.",
	"horizon_survey":               "Horizon survey",
	"passes_plotted":               "passes plotted",
	"sky_quality_map":              "Reception quality sky map",
	"sky_quality_map_help":         "Each point is a past pass, placed where it reached its highest elevation and colored by the peak SNR SatDump reported. Clusters of weak or failed passes show where the horizon is obstructed.",
	"sky_quality_map_missing":      "The sky map is redrawn after every pass once passes have been captured.",
	"successful_delete_capture":    "Successfully deleted capture",
	"successful_delete_pass":       "Successfully deleted pass",
	"travel_direction":             "Direction",
	"view_capture":                 "View capture",
	"login":                        "Log in",
	"logout":                       "Log out",
	"username":                     "Username",
	"password":                     "Password",
	"login_failed":                 "Wrong username or password",
	"login_required":               "The admin pages require a login",
}

// L looks up a panel string; unknown keys render as themselves so a missing
// translation is visible rather than blank.
func L(key string) string {
	if s, ok := lang[key]; ok {
		return s
	}
	return key
}
